// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart' show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDrrE40zBdHgG-nvLOt-J_1MSXh9Y--0_k',
    appId: '1:975131849609:web:5a2ffad13bc956bdf42758',
    messagingSenderId: '975131849609',
    projectId: 'healthify-flutter-application',
    authDomain: 'healthify-flutter-application.firebaseapp.com',
    storageBucket: 'healthify-flutter-application.appspot.com',
    measurementId: 'G-BDY8GY4GQC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAwfMcCKOFw2VT6ZY_D2RX7tLU04RmOxo',
    appId: '1:975131849609:android:c683de47ee3c0646f42758',
    messagingSenderId: '975131849609',
    projectId: 'healthify-flutter-application',
    storageBucket: 'healthify-flutter-application.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDqUMJSsx3PgRtwR62xGPzMltrH75DgXek',
    appId: '1:975131849609:ios:e6899b8a9faff070f42758',
    messagingSenderId: '975131849609',
    projectId: 'healthify-flutter-application',
    storageBucket: 'healthify-flutter-application.appspot.com',
    iosBundleId: 'com.example.flutterApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDqUMJSsx3PgRtwR62xGPzMltrH75DgXek',
    appId: '1:975131849609:ios:fd8af1fc44e18e98f42758',
    messagingSenderId: '975131849609',
    projectId: 'healthify-flutter-application',
    storageBucket: 'healthify-flutter-application.appspot.com',
    iosBundleId: 'com.example.flutterApp.RunnerTests',
  );
}
